### ISSUE TITLE
[Bug]: "Token could not be verified. Is it correct?"

### ISSUE THREAD

**Issue by jlhjlh** [Curetix/mailflare-extension#12]
### What is this bug about?

Receiving an error: "Token could not be verified. Is it correct?" Even though I followed the instructions.
![image](https://github.com/Curetix/mailflare-extension/assets/10662400/74951add-3484-4d6f-8d51-2b20dd0254bd)

<img width="396" alt="image" src="https://github.com/Curetix/mailflare-extension/assets/10662400/e8041360-d485-48f8-8cdc-c45e5a43121d">

I check the token using curl:

```{"result":{"id":"asdfasdfasdf","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}%```

and it's accepted.

### Steps to reproduce

Create a new token with the specified parameters and paste it into the plugin input box.

### Additional info

I will say the error is coming back SO FAST from the plugin that I don't think it's even checking it. 

`Firefox: 123.0.1 (64-bit) on Mac. Mailflare: Version 1.3.0`

**Comment by Curetix** [comment]
Hmm, I can't reproduce the issue on my end. Since you're using Firefox, please check if you have [granted the necessary permissions](https://github.com/Curetix/mailflare-extension?tab=readme-ov-file#firefox). Otherwise, could you share a screenshot of the developer console? (right click on the extension popup -> Inspect)

**Comment by jlhjlh** [comment]
OMFG, I didn't give it permissions. I skipped over that part once I clicked the install button.

I have some thoughts about functionality though. Should I paste them here or add a new ticket or perhaps fork the repo?

**Comment by Curetix** [comment]
> OMFG, I didn't give it permissions. I skipped over that part once I clicked the install button since it took me to a new window.
> 
> I have some thoughts about functionality though. Should I paste them here or add a new ticket or perhaps fork the repo?

No problem. I think Firefox treats host permissions as optional since I updated the extension to Manifest v3, it doesn't even ask about those during installation. I've added a warning when the permission is missing, will release that update shortly.

I also opened up [Discussions](https://github.com/Curetix/mailflare-extension/discussions/categories/ideas), you can gladly create a post about your ideas there.
