### ISSUE TITLE
[Feature]: Support subdomains

### ISSUE THREAD

**Issue by claabs** [Curetix/mailflare-extension#26]
### Feature Description

In the readme, it mentions the limitation:

> Subdomains cannot use Email Routing to forward emails, unless they are part of an Enterprise account.

However that doesn't appear to be mentioned on the [Known Limitations page](https://developers.cloudflare.com/email-routing/postmaster/#known-limitations) anymore. Rules can be created for specific subdomains in CloudFlare.

If you create a subdomain `a.example.com`, it does not appear anywhere when creating an alias in MailFlare.

### Solution idea

Ideally, the subdomain would be a available in the **Domain** field when creating a new alias.

### Additional info

This would be a helpful feature, as I'm using MailFlare until I hit the 200 rule limit, then I'll likely move to a paid service. Keeping all the aliases on a subdomain means easy MX record migration to a paid alias service.

**Comment by Curetix** [comment]
Yup you're right, looks like Clouflare rolled out this feature to all users. I'll figure out a way to add this to MailFlare, I never considered it before because of the Paywall.

Keep in mind you still need to set up Email Routing for your subdomain separately in the Email Routing settings of the domain:

![image](https://github.com/user-attachments/assets/59350b26-b019-4069-9ebe-9ee001e74b66)
